/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Data.DataSQL;
import Data.ShareData;
import java.awt.Image;
import java.awt.Toolkit;
import java.lang.System.Logger;
import java.net.URL;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Student;

/**
 *
 * @author USER
 */
public class MainForm extends javax.swing.JFrame {

    private QLSVPannel qlsvpannel;
    private QLDiemPannel qldpannel;
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(getExtendedState());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        LoginDialog login = new LoginDialog(this, true);
        login.setVisible(true);
        this.setTitle("Student Manager");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_gioiTinh = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jButton_dangXuat = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton_QLSV = new javax.swing.JButton();
        jButton_QLD = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jButton_gioiThieu = new javax.swing.JButton();
        jTabbedPane_MainForm = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel_LoginName = new javax.swing.JLabel();
        jLabel_vaiTro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_heThong = new javax.swing.JMenu();
        jMenuItem_dangXuat = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Thoat = new javax.swing.JMenuItem();
        jMenu_quanLy = new javax.swing.JMenu();
        jMenuItem_QLSV = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_QLD = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_noiDung = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_gioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 740));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(0, 153, 204));
        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToolBar1.setRollover(true);

        jButton_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jButton_dangXuat.setText("Đăng xuất");
        jButton_dangXuat.setBorder(null);
        jButton_dangXuat.setFocusable(false);
        jButton_dangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_dangXuat.setOpaque(false);
        jButton_dangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_dangXuat);
        jToolBar1.add(jSeparator6);

        jButton_QLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/student (1).png"))); // NOI18N
        jButton_QLSV.setText("Quản lý sinh viên");
        jButton_QLSV.setBorder(null);
        jButton_QLSV.setFocusable(false);
        jButton_QLSV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_QLSV.setOpaque(false);
        jButton_QLSV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_QLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QLSVActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_QLSV);

        jButton_QLD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/marking.png"))); // NOI18N
        jButton_QLD.setText("Quản lý điểm");
        jButton_QLD.setBorder(null);
        jButton_QLD.setFocusable(false);
        jButton_QLD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_QLD.setOpaque(false);
        jButton_QLD.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_QLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QLDActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_QLD);
        jToolBar1.add(jSeparator8);

        jButton_gioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/about.png"))); // NOI18N
        jButton_gioiThieu.setText("Giới thiệu");
        jButton_gioiThieu.setBorder(null);
        jButton_gioiThieu.setFocusable(false);
        jButton_gioiThieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_gioiThieu.setOpaque(false);
        jButton_gioiThieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton_gioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_gioiThieuActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_gioiThieu);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 60));

        jTabbedPane_MainForm.setBackground(new java.awt.Color(51, 0, 102));
        jTabbedPane_MainForm.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jTabbedPane_MainForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1110, 690));

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_LoginName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_LoginName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_LoginName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_vaiTro.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel_vaiTro.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_vaiTro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_LoginName, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
            .addComponent(jLabel_vaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel_LoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_vaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, 60));

        jMenu_heThong.setText("Hệ thống");

        jMenuItem_dangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        jMenuItem_dangXuat.setText("Đăng xuất");
        jMenuItem_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_dangXuatActionPerformed(evt);
            }
        });
        jMenu_heThong.add(jMenuItem_dangXuat);
        jMenu_heThong.add(jSeparator3);

        jMenuItem_Thoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/power-off.png"))); // NOI18N
        jMenuItem_Thoat.setText("Thoát");
        jMenuItem_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ThoatActionPerformed(evt);
            }
        });
        jMenu_heThong.add(jMenuItem_Thoat);

        jMenuBar1.add(jMenu_heThong);

        jMenu_quanLy.setText("Quản lý");

        jMenuItem_QLSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_QLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/student (1).png"))); // NOI18N
        jMenuItem_QLSV.setText("Quản lý sinh viên");
        jMenuItem_QLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_QLSVActionPerformed(evt);
            }
        });
        jMenu_quanLy.add(jMenuItem_QLSV);
        jMenu_quanLy.add(jSeparator4);

        jMenuItem_QLD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_QLD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/marking.png"))); // NOI18N
        jMenuItem_QLD.setText("Quản lý điểm");
        jMenuItem_QLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_QLDActionPerformed(evt);
            }
        });
        jMenu_quanLy.add(jMenuItem_QLD);

        jMenuBar1.add(jMenu_quanLy);

        jMenu3.setText("Trợ giúp");

        jMenuItem_noiDung.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_noiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/question-sign.png"))); // NOI18N
        jMenuItem_noiDung.setText("Nội dung");
        jMenuItem_noiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_noiDungActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_noiDung);
        jMenu3.add(jSeparator5);

        jMenuItem_gioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem_gioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/about.png"))); // NOI18N
        jMenuItem_gioiThieu.setText("Giới thiệu");
        jMenuItem_gioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gioiThieuActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_gioiThieu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_noiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_noiDungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_noiDungActionPerformed

    private void jMenuItem_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_ThoatActionPerformed

    private void jMenuItem_QLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_QLSVActionPerformed
        if(qlsvpannel == null ){
        qlsvpannel = new QLSVPannel();
        jTabbedPane_MainForm.addTab("Quản lý sinh viên",qlsvpannel);
        }
        jTabbedPane_MainForm.setSelectedComponent(qlsvpannel);
    }//GEN-LAST:event_jMenuItem_QLSVActionPerformed

    private void jMenuItem_QLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_QLDActionPerformed
        if(qldpannel == null){
            qldpannel = new QLDiemPannel();
            jTabbedPane_MainForm.addTab("Quản lý điểm", qldpannel);
        }
        jTabbedPane_MainForm.setSelectedComponent(qldpannel);
    }//GEN-LAST:event_jMenuItem_QLDActionPerformed

    private void jButton_gioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_gioiThieuActionPerformed
        AboutUsDialog abd = new AboutUsDialog(this, true);
        abd.setVisible(true);
    }//GEN-LAST:event_jButton_gioiThieuActionPerformed

    private void jMenuItem_gioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gioiThieuActionPerformed
        jButton_gioiThieuActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem_gioiThieuActionPerformed

    private void jButton_QLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QLSVActionPerformed
        jMenuItem_QLSVActionPerformed(evt);
    }//GEN-LAST:event_jButton_QLSVActionPerformed

    private void jButton_QLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QLDActionPerformed
        jMenuItem_QLDActionPerformed(evt);
    }//GEN-LAST:event_jButton_QLDActionPerformed

    private void jButton_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dangXuatActionPerformed

       LoginDialog login = new LoginDialog(this, true);
       login.setVisible(true);
       
       processLoginSucessfull();
      
    }//GEN-LAST:event_jButton_dangXuatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        processLoginSucessfull();
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_dangXuatActionPerformed
       LoginDialog login = new LoginDialog(this, true);
       login.setVisible(true);
  
    }//GEN-LAST:event_jMenuItem_dangXuatActionPerformed
    private void processLoginSucessfull(){
        jLabel_LoginName.setText(ShareData.NguoiDangNhap.getTenDangNhap());
        jLabel_vaiTro.setText(ShareData.NguoiDangNhap.getVaiTro());
        jTabbedPane_MainForm.removeAll();
        qlsvpannel = null;
        qldpannel = null;
        
        if(ShareData.NguoiDangNhap.getVaiTro().equals("Quản trị viên (Admin)")){
            jMenuItem_QLD.setEnabled(true);
            jMenuItem_QLSV.setEnabled(true);
            jButton_QLSV.setEnabled(true);
            jButton_QLD.setEnabled(true);
        }
        else if(ShareData.NguoiDangNhap.getVaiTro().equals("Giảng viên")){
            jMenuItem_QLSV.setEnabled(false);
            jMenuItem_QLD.setEnabled(true);
             jButton_QLSV.setEnabled(false);
            jButton_QLD.setEnabled(true);
        }
        else if(ShareData.NguoiDangNhap.getVaiTro().equals("Đào tạo")){
            jMenuItem_QLSV.setEnabled(true);
            jMenuItem_QLD.setEnabled(false);
             jButton_QLSV.setEnabled(true);
            jButton_QLD.setEnabled(false);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_gioiTinh;
    private javax.swing.JButton jButton_QLD;
    private javax.swing.JButton jButton_QLSV;
    private javax.swing.JButton jButton_dangXuat;
    private javax.swing.JButton jButton_gioiThieu;
    private javax.swing.JLabel jLabel_LoginName;
    private javax.swing.JLabel jLabel_vaiTro;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_QLD;
    private javax.swing.JMenuItem jMenuItem_QLSV;
    private javax.swing.JMenuItem jMenuItem_Thoat;
    private javax.swing.JMenuItem jMenuItem_dangXuat;
    private javax.swing.JMenuItem jMenuItem_gioiThieu;
    private javax.swing.JMenuItem jMenuItem_noiDung;
    private javax.swing.JMenu jMenu_heThong;
    private javax.swing.JMenu jMenu_quanLy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator8;
    public javax.swing.JTabbedPane jTabbedPane_MainForm;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
